### ISSUE TITLE
The last column of every record is JSON

### ISSUE THREAD

**Issue by sjackman** [pmelsted/GFA-spec#15]
@noporpoise proposes in https://github.com/pmelsted/GFA-spec/issues/7#issuecomment-128014521 that the last column of every record is JSON. JSON would replace the current `TAG:TYPE:VALUE` system.

**Comment by sjackman** [comment]
> JSON would replace the current TAG:TYPE:VALUE system.

Was that your intention, Isaac, to replace the `TAG:TYPE:VALUE` system?

**Comment by sjackman** [comment]
Invariably the type system of arbitrary tags gets complex, and we'll end up reinventing JSON anyway. Let's just adopt JSON. Please.

**Comment by ekg** [comment]
I think this is a nice move. No one needs to write parsers for these fields!

This should help us focus on the representation of the sequence graph.

**Comment by noporpoise** [comment]
+1. Thanks.

**Comment by noporpoise** [comment]
Shall we probibit new line characters from appearing in the JSON object? I think we can still allow spaces and tabs. 

My preference would be full JSON support but I understand other people want a single-line-per-entry format that they can `awk` and `grep`.

**Comment by ekg** [comment]
How does line-delimited JSON do it?

**Comment by sjackman** [comment]
:+1: on prohibiting new-line characters in the JSON object. I'm okay with spaces. I'd prefer no tabs.

**Comment by pmelsted** [comment]
I think JSON has enough library support to warrant this. Mostly this would be an issue for GFA as input files, assemblers can produce fixed JSON docs. Also agree with no tabs and no newlines.

**Comment by sjackman** [comment]
If we go ahead with this, I suggest we bump the header version number of GFA. There are a handful of GFA implementations, and it would be nice to punish the early adopters.

**Comment by sjackman** [comment]
@pb-jchin @jts @lh3
Your thoughts on changing the last column of GFA from the SAM format to JSON?

**Comment by pb-jchin** [comment]
@sjackman I like it in general, but I have not checked the whole JSON spec yet.  JSON string without "\n", "\r", or "\r\n" should be good.

**Comment by sjackman** [comment]
Sounds like we have a consensus. @noporpoise Would you like to write the PR?

**Comment by lh3** [comment]
No, I strongly object to JSON.

**Comment by ekg** [comment]
Actually I also object to enforcing JSON for every thing. Could we
generalize this to allow for arbitrary strings (provided newlines are
escaped)? I simply don't want to focus the spec on the annotations that
people will try to stash in GFA.

**Comment by sjackman** [comment]
There's an advantage in using an existing and well-defined syntax, so that we can focus on semantics. The syntax of VCF, for example is quite complicated, and would have been better off, I think, using JSON for the extended fields. We can specify a particular subset of JSON that is valid in a GFA file.
`{"LN":100,"RC":1234}` is nearly as easy to parse as `LN:i:100 RC:i:1234` with a roll-your-own parser.

**Comment by lh3** [comment]
Sorry, I was away for something else and did not explain why I think JSON is not the right choice.

JSON is good for structured data. For example, we can put arrays in hash tables then in other arrays. For GFA, though, I think a simple list of typed key-value pairs suffice most of time. If we allow arbitrary escaping, we can have something like `JS:Z:{"len":100,"string":"abc"}` for structured data, though I have not had such need for SAM.

I have written a hobby [JSON parser][1] myself. I feel it is much trickier to parse JSON than to parse SAM key-value pairs. Most developers will choose "proper" 3rd-party JSON parsers. That adds an unnecessary dependency. In addition, in memory, a JSON object is also fatter, which can be a concern for huge graphs.

[1]: https://github.com/attractivechaos/klib/blob/master/kson.h

**Comment by sjackman** [comment]
I wouldn't want a hash table per graph object either. Not pretty. Perhaps we should just stick with the existing format then, and keep in mind that if a proposed new optional field is ever more complicated than a simple scalar, we should consider encoding it in JSON.

@noporpoise What's your feeling on this?

**Comment by sjackman** [comment]
I am also hesitant to break the existing GFA implementations.

**Comment by pmelsted** [comment]
I completely understand your library reservations @lh3, especially for those of us coding in c/c++/c++11. I think we can have a bit of both worlds by specifying a JSON tag `JS` of type `J` where it has to be the last field/tag of the line and include no `\r,\n,\t`.

So if you don't require JSON as input you can simply skip to the end of the line if you see a `JS` tag. I don't think this would break the awkability of the format.

I can't think of any applications that absolutely need JSON, but specific applications might want to embed some info there.

**Comment by pb-jchin** [comment]
Hi, @lh3 @pmelsted, the "B" and "E" notation that I am using is from Gene Myers' 2005 paper (http://bioinformatics.oxfordjournals.org/content/21/suppl_2/ii79.abstract). On the second page, it describes how to construct directed (not bi-directed) string graph. Here is some excerpt of the text:  

> For each such read f there will be two vertices, f.B and f.E, one for each end of the read, in the string graph.

and

> one adds a directed edge labeled with the non-matched or overhanging sequence at each end of the proper overlap between two reads

Later, the author describes how the "directed graph" is related to the "bidirected graph" and the equivalence to ealier overlap graph 

>At this juncture observe that because no read contains the other, every composite edge e = v1 → v2 → v3··· → vn has a complementary edge comp(e) = comp(vn) → ...comp(v3) → comp(v2) → comp(v1) where comp(v) is the other end of the read for f. That is, if v = f.B then comp(v) = f.E and if v = f.E then comp(v) = f.B. This property implies that we may instead think of the endpoint pairs as a single vertex with bidirected edges corresponding to an edge and its complement, where an arrowhead is directed into a vertex if the edge to its .

Notice that, in the definition of the string graph, it is different from joining the ends of two arbitrary segments.  There is alway sub-string associated with each edge from a single read while the the edges are always linking vertices from two reads.  The order of the vertices label is important as it represents the directed edges. This is different from the "J" proposal if I understand it right. 

While bidirectional graph representation is indeed more compact than the directed graph + duality tracking representation for assembly string graph.  The benefit of using directed graph is that it is easier to apply most graph algorithms using existing graph library without constructing customerized classes or objects.  It is also easier for visualization and contructing sequences by simply concatente the edges without explicilty specific orientation to use. The downside is one needs to be sure to preserve the duality symmetry for any operations modifying the graph. 

My preference is that if we like to use the "B" and "E" notation and call the GFA represetning string graph, it will be better to stick with the definition used in Gene's paper to avoid future confusion. Otherwise, it might be better just using "+" and "-" and make it clear that GFA is for overlap graph rather than Gene Myers' version of string graph.   The two different graphs are isomorphic beside some notation differences in theory, so one can convert the graph if necessary.  However, it will be useful to keep some extra data for each line of "L" to make conversions and some operations easier.

**Comment by lh3** [comment]
I think we can just have a new type `J`. We allow one or multiple tags to have `J` type. For example,
```
S  contig1   *   AB:J:{"abc":5}  CD:J:{"def":[5.2,7]} LN:i:10
```

**Comment by sjackman** [comment]
I agree with Heng that multiple JSON fields in any position could be useful. I'll make this proposal in a pull request.
