### ISSUE TITLE
Specify different sequences for two complementary strands?

### ISSUE THREAD

**Issue by rrwick** [pmelsted/GFA-spec#21]
For a given segment in a graph, there are two corresponding sequences, the forward and the reverse complement.  As I understand GFA, only the forward sequence is specified and the reverse complement sequence could be deduced if needed.  Is that right?

The reason I ask is that in Velvet graphs, the forward and reverse sequences of a segment are NOT exact complements - they are shifted.  I tried to illustrate this on the 'Assembler differences' page of the Bandage wiki: https://github.com/rrwick/Bandage/wiki/Assembler-differences

I couldn't see a way for GFA to support this kind of arrangement.  So here's my thought for an addition: have an optional field in segment lines of OR (for orientation) which specifies the strand.  E.g.:

```
S	segment_name	CTGATTG	OR:Z:+	LN:i:7
S	segment_name	CAGTCTA	OR:Z:-	LN:i:7
```

With this, you could have two segment lines with the same name if and only if one has a '+' orientation and the other has a '-', and then you could manually specify the sequences for each.  Thoughts?

**Comment by sjackman** [comment]
Hi, Ryan. The sequence that overlaps neighbouring segments should not be ellided in GFA, as Velvet does in it's LastGraph format. This example segment would be represented in GFA as

```
S segment_name TAGACTGATTG LN:i:11
```

**Comment by pmelsted** [comment]
Hi Ryan. It's an interesting thought, but I think that Velvet is alone in producing this sort of format.

The issue is that the segments in velvet store all but the first (k-1) in forward and reverse complements. If the contig has length greater than 2k-1 you can reconstruct the sequence, however if they're shorter you have to build this info from the graph using BFS or something like it.

I think the community would best be served by a tool to convert the LastGraph format to GFA, rather than  complicating the GFA. I have a draft of such a thing available somewhere, but there were some pieces missing.

Just to clarify, yes only one strand is stored per contig and it is deemed to be the forward one.

**Comment by rrwick** [comment]
Okay, that makes sense.  Could there be any other realistic scenario where the two strands in a contig would not be exact reverse complements of each other?  I can't think of any in particular - I'm just wondering if there would be any other justification for being able to specify each strand sequence, other than for Velvet graphs.

**Comment by sjackman** [comment]
Not that I can think of. GFA defines the sequence of `1-` to be exactly the reverse complement of `1+`.

**Comment by sjackman** [comment]
I do agree with Pall that a converter from Velvet LastGraph format to GFA would be quite useful to the community.

**Comment by lh3** [comment]
gfatools.js has a converter for velvet LastGraph. It shifts the two segments in a node to get a GFA contig. A problem is that it may need to fill "N" if the two segments are shorter than the k-mer length. I thought to infer "N" from overlapping contigs, but gave up in the end due to the extra complexity.

**Comment by rrwick** [comment]
In Bandage, I've been working on adding support for editing and saving graphs, and (at least for the moment), I'm using GFA as the sole output format.  That's why I was wondering about Velvet graphs, because one can load a Velvet graph into Bandage, possibly make alterations, and then save it as a GFA.

Based on this discussion, I've dropped the idea of separately saving both strands of the sequence and instead added logic to extend Velvet segments, like in Shaun's example above.  And Bandage will look in neighbouring segments to fill in the sequence if necessary.

So in a sense, I have written a LastGraph to GFA conversion tool, in GUI form: load a LastGraph in Bandage and then save it to GFA.  It's currently in the development branch of Bandage, but it should be in the next release (0.7.0) in the not-too-distant future.  Making this conversion possible from the command line shouldn't be too hard and is on my to do list.

Thanks for the feedback, everyone!
